# Generated by Django 5.2.10 on 2026-02-07 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='รหัสนิสิต')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, verbose_name='รหัสวิชา')),
                ('subject_name', models.CharField(max_length=100, verbose_name='ชื่อวิชา')),
                ('section', models.CharField(default='1', max_length=10, verbose_name='หมู่เรียน')),
                ('exam_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สอบ')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='เวลาเริ่มสอบ')),
                ('duration_minutes', models.IntegerField(default=120, verbose_name='เวลาที่ใช้สอบ (นาที)')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='ห้องสอบ')),
                ('total_questions', models.IntegerField(default=100, verbose_name='จำนวนข้อ')),
                ('answer_key', models.JSONField(default=dict, verbose_name='เฉลย (JSON)')),
                ('key_image', models.ImageField(blank=True, null=True, upload_to='uploads/keys/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='exams', to='grading.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_ocr', models.CharField(max_length=50, verbose_name='รหัสที่อ่านได้')),
                ('score', models.IntegerField(default=0, verbose_name='คะแนน')),
                ('original_image', models.ImageField(upload_to='uploads/papers/')),
                ('graded_image', models.ImageField(blank=True, null=True, upload_to='uploads/graded/')),
                ('status', models.CharField(choices=[('OCR', 'ตรวจจากเครื่อง (OCR Scanned)'), ('EDITING', 'กำลังแก้ไข (Editing)'), ('FINISHED', 'แก้ไขเสร็จสิ้น (Manual Finished)')], default='OCR', max_length=20)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grading.exam')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.student')),
            ],
        ),
    ]
