# Generated by Django 5.2.10 on 2026-03-27 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='รหัสนิสิต')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, verbose_name='รหัสวิชา')),
                ('subject_name', models.CharField(max_length=100, verbose_name='ชื่อวิชา')),
                ('section', models.CharField(default='1', max_length=10, verbose_name='หมู่เรียน')),
                ('exam_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สอบ')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='เวลาเริ่มสอบ')),
                ('duration_minutes', models.IntegerField(default=120, verbose_name='เวลาที่ใช้สอบ (นาที)')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='ห้องสอบ')),
                ('total_questions', models.IntegerField(default=100, verbose_name='จำนวนข้อ')),
                ('answer_key', models.JSONField(default=dict, verbose_name='เฉลย (JSON)')),
                ('key_image', models.ImageField(blank=True, null=True, upload_to='uploads/keys/')),
                ('roster_file', models.FileField(blank=True, null=True, upload_to='uploads/rosters/', verbose_name='ไฟล์รายชื่อนิสิต')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มรายชื่อ')),
                ('status', models.CharField(default='ACTIVE', max_length=20, verbose_name='สถานะ')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.student')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='exams', through='grading.ExamEnrollment', to='grading.student'),
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_ocr', models.CharField(max_length=50, verbose_name='รหัสที่อ่านได้')),
                ('score', models.IntegerField(default=0, verbose_name='คะแนน')),
                ('original_image', models.ImageField(upload_to='uploads/papers/')),
                ('graded_image', models.ImageField(blank=True, null=True, upload_to='uploads/graded/')),
                ('debug_image', models.ImageField(blank=True, null=True, upload_to='uploads/graded/')),
                ('status', models.CharField(choices=[('BLUE', 'ตรวจผ่าน (ไม่มีข้อผิดพลาด)'), ('RED', 'พบข้อผิดพลาด (ต้องตรวจสอบ)'), ('GREEN', 'ตรวจสอบด้วยคนแล้ว (Verified)')], default='RED', max_length=20)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grading.exam')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.student')),
            ],
        ),
    ]
