# Generated by Django 5.2.10 on 2026-01-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='key_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
