# Generated by Django 5.2.10 on 2026-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_exam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='roster_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/rosters/', verbose_name='ไฟล์รายชื่อนิสิต'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='debug_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/graded/'),
        ),
    ]
