# Generated by Django 5.2.10 on 2026-01-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_exam_key_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
