# Generated by Django 5.2.10 on 2026-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_exam_roster_file_studentresult_debug_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='status',
            field=models.CharField(choices=[('BLUE', 'ตรวจผ่าน (ไม่มีข้อผิดพลาด)'), ('RED', 'พบข้อผิดพลาด (ต้องตรวจสอบ)'), ('GREEN', 'ตรวจสอบด้วยคนแล้ว (Verified)')], default='RED', max_length=20),
        ),
    ]
