# Generated by Django 5.2.10 on 2026-01-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_student_exam_course_code_exam_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
