# Generated by Django 5.2.10 on 2026-01-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='grading.subject'),
        ),
    ]
